// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sms.proto

package com.huiyou.dp.service.protocol;

public final class Sms {
  private Sms() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SendIdentifyingCodeRequestOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;
    /**
     * <code>optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;</code>
     */
    boolean hasSmsSendType();
    /**
     * <code>optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;</code>
     */
    com.huiyou.dp.service.protocol.Common.SmsSendType getSmsSendType();

    // optional string mobile_num = 2;
    /**
     * <code>optional string mobile_num = 2;</code>
     */
    boolean hasMobileNum();
    /**
     * <code>optional string mobile_num = 2;</code>
     */
    java.lang.String getMobileNum();
    /**
     * <code>optional string mobile_num = 2;</code>
     */
    com.google.protobuf.ByteString
        getMobileNumBytes();
  }
  /**
   * Protobuf type {@code com.huiyou.dp.service.protocol.SendIdentifyingCodeRequest}
   *
   * <pre>
   * PATH: /sms/sendIdentifyingCode
   * 发送验证码，有效期20分钟
   * </pre>
   */
  public static final class SendIdentifyingCodeRequest extends
      com.google.protobuf.GeneratedMessageLite
      implements SendIdentifyingCodeRequestOrBuilder {
    // Use SendIdentifyingCodeRequest.newBuilder() to construct.
    private SendIdentifyingCodeRequest(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private SendIdentifyingCodeRequest(boolean noInit) {}

    private static final SendIdentifyingCodeRequest defaultInstance;
    public static SendIdentifyingCodeRequest getDefaultInstance() {
      return defaultInstance;
    }

    public SendIdentifyingCodeRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private SendIdentifyingCodeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.huiyou.dp.service.protocol.Common.SmsSendType value = com.huiyou.dp.service.protocol.Common.SmsSendType.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                smsSendType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              mobileNum_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<SendIdentifyingCodeRequest> PARSER =
        new com.google.protobuf.AbstractParser<SendIdentifyingCodeRequest>() {
      public SendIdentifyingCodeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendIdentifyingCodeRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendIdentifyingCodeRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;
    public static final int SMS_SEND_TYPE_FIELD_NUMBER = 1;
    private com.huiyou.dp.service.protocol.Common.SmsSendType smsSendType_;
    /**
     * <code>optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;</code>
     */
    public boolean hasSmsSendType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;</code>
     */
    public com.huiyou.dp.service.protocol.Common.SmsSendType getSmsSendType() {
      return smsSendType_;
    }

    // optional string mobile_num = 2;
    public static final int MOBILE_NUM_FIELD_NUMBER = 2;
    private java.lang.Object mobileNum_;
    /**
     * <code>optional string mobile_num = 2;</code>
     */
    public boolean hasMobileNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string mobile_num = 2;</code>
     */
    public java.lang.String getMobileNum() {
      java.lang.Object ref = mobileNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mobileNum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mobile_num = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMobileNumBytes() {
      java.lang.Object ref = mobileNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobileNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      smsSendType_ = com.huiyou.dp.service.protocol.Common.SmsSendType.SmsSendType_REGISTER;
      mobileNum_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, smsSendType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMobileNumBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, smsSendType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMobileNumBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.huiyou.dp.service.protocol.SendIdentifyingCodeRequest}
     *
     * <pre>
     * PATH: /sms/sendIdentifyingCode
     * 发送验证码，有效期20分钟
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest, Builder>
        implements com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequestOrBuilder {
      // Construct using com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        smsSendType_ = com.huiyou.dp.service.protocol.Common.SmsSendType.SmsSendType_REGISTER;
        bitField0_ = (bitField0_ & ~0x00000001);
        mobileNum_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest getDefaultInstanceForType() {
        return com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest.getDefaultInstance();
      }

      public com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest build() {
        com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest buildPartial() {
        com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest result = new com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.smsSendType_ = smsSendType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mobileNum_ = mobileNum_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest other) {
        if (other == com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest.getDefaultInstance()) return this;
        if (other.hasSmsSendType()) {
          setSmsSendType(other.getSmsSendType());
        }
        if (other.hasMobileNum()) {
          bitField0_ |= 0x00000002;
          mobileNum_ = other.mobileNum_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;
      private com.huiyou.dp.service.protocol.Common.SmsSendType smsSendType_ = com.huiyou.dp.service.protocol.Common.SmsSendType.SmsSendType_REGISTER;
      /**
       * <code>optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;</code>
       */
      public boolean hasSmsSendType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;</code>
       */
      public com.huiyou.dp.service.protocol.Common.SmsSendType getSmsSendType() {
        return smsSendType_;
      }
      /**
       * <code>optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;</code>
       */
      public Builder setSmsSendType(com.huiyou.dp.service.protocol.Common.SmsSendType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        smsSendType_ = value;
        
        return this;
      }
      /**
       * <code>optional .com.huiyou.dp.service.protocol.SmsSendType sms_send_type = 1;</code>
       */
      public Builder clearSmsSendType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        smsSendType_ = com.huiyou.dp.service.protocol.Common.SmsSendType.SmsSendType_REGISTER;
        
        return this;
      }

      // optional string mobile_num = 2;
      private java.lang.Object mobileNum_ = "";
      /**
       * <code>optional string mobile_num = 2;</code>
       */
      public boolean hasMobileNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string mobile_num = 2;</code>
       */
      public java.lang.String getMobileNum() {
        java.lang.Object ref = mobileNum_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mobileNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mobile_num = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMobileNumBytes() {
        java.lang.Object ref = mobileNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobileNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile_num = 2;</code>
       */
      public Builder setMobileNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mobileNum_ = value;
        
        return this;
      }
      /**
       * <code>optional string mobile_num = 2;</code>
       */
      public Builder clearMobileNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mobileNum_ = getDefaultInstance().getMobileNum();
        
        return this;
      }
      /**
       * <code>optional string mobile_num = 2;</code>
       */
      public Builder setMobileNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mobileNum_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.huiyou.dp.service.protocol.SendIdentifyingCodeRequest)
    }

    static {
      defaultInstance = new SendIdentifyingCodeRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.huiyou.dp.service.protocol.SendIdentifyingCodeRequest)
  }

  public interface SendIdentifyingCodeResponseOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;
    /**
     * <code>optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;</code>
     */
    com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode getErrCode();

    // optional string err_msg = 2;
    /**
     * <code>optional string err_msg = 2;</code>
     */
    boolean hasErrMsg();
    /**
     * <code>optional string err_msg = 2;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string err_msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse}
   */
  public static final class SendIdentifyingCodeResponse extends
      com.google.protobuf.GeneratedMessageLite
      implements SendIdentifyingCodeResponseOrBuilder {
    // Use SendIdentifyingCodeResponse.newBuilder() to construct.
    private SendIdentifyingCodeResponse(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private SendIdentifyingCodeResponse(boolean noInit) {}

    private static final SendIdentifyingCodeResponse defaultInstance;
    public static SendIdentifyingCodeResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SendIdentifyingCodeResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private SendIdentifyingCodeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode value = com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                errCode_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<SendIdentifyingCodeResponse> PARSER =
        new com.google.protobuf.AbstractParser<SendIdentifyingCodeResponse>() {
      public SendIdentifyingCodeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendIdentifyingCodeResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendIdentifyingCodeResponse> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode}
     */
    public enum ErrorCode
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>ERR_OK = 0;</code>
       */
      ERR_OK(0, 0),
      /**
       * <code>ERR_REQUEST_INVALID = 1;</code>
       */
      ERR_REQUEST_INVALID(1, 1),
      /**
       * <code>ERR_MOBILE_NUM_PATTERN = 2;</code>
       *
       * <pre>
       *手机号格式错误
       * </pre>
       */
      ERR_MOBILE_NUM_PATTERN(2, 2),
      /**
       * <code>ERR_MOBILE_NUM_INVALID = 3;</code>
       *
       * <pre>
       *号码中含有无效号码或不在规定的号段或为免打扰号码
       * </pre>
       */
      ERR_MOBILE_NUM_INVALID(3, 3),
      /**
       * <code>ERR_EXCEED_SEND_COUNT = 4;</code>
       *
       * <pre>
       *同一号码相同内容发送次数太多
       * </pre>
       */
      ERR_EXCEED_SEND_COUNT(4, 4),
      /**
       * <code>ERR_UNKNOWN = 5;</code>
       */
      ERR_UNKNOWN(5, 5),
      ;

      /**
       * <code>ERR_OK = 0;</code>
       */
      public static final int ERR_OK_VALUE = 0;
      /**
       * <code>ERR_REQUEST_INVALID = 1;</code>
       */
      public static final int ERR_REQUEST_INVALID_VALUE = 1;
      /**
       * <code>ERR_MOBILE_NUM_PATTERN = 2;</code>
       *
       * <pre>
       *手机号格式错误
       * </pre>
       */
      public static final int ERR_MOBILE_NUM_PATTERN_VALUE = 2;
      /**
       * <code>ERR_MOBILE_NUM_INVALID = 3;</code>
       *
       * <pre>
       *号码中含有无效号码或不在规定的号段或为免打扰号码
       * </pre>
       */
      public static final int ERR_MOBILE_NUM_INVALID_VALUE = 3;
      /**
       * <code>ERR_EXCEED_SEND_COUNT = 4;</code>
       *
       * <pre>
       *同一号码相同内容发送次数太多
       * </pre>
       */
      public static final int ERR_EXCEED_SEND_COUNT_VALUE = 4;
      /**
       * <code>ERR_UNKNOWN = 5;</code>
       */
      public static final int ERR_UNKNOWN_VALUE = 5;


      public final int getNumber() { return value; }

      public static ErrorCode valueOf(int value) {
        switch (value) {
          case 0: return ERR_OK;
          case 1: return ERR_REQUEST_INVALID;
          case 2: return ERR_MOBILE_NUM_PATTERN;
          case 3: return ERR_MOBILE_NUM_INVALID;
          case 4: return ERR_EXCEED_SEND_COUNT;
          case 5: return ERR_UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
              public ErrorCode findValueByNumber(int number) {
                return ErrorCode.valueOf(number);
              }
            };

      private final int value;

      private ErrorCode(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode)
    }

    private int bitField0_;
    // optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;
    public static final int ERR_CODE_FIELD_NUMBER = 1;
    private com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode errCode_;
    /**
     * <code>optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;</code>
     */
    public com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode getErrCode() {
      return errCode_;
    }

    // optional string err_msg = 2;
    public static final int ERR_MSG_FIELD_NUMBER = 2;
    private java.lang.Object errMsg_;
    /**
     * <code>optional string err_msg = 2;</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string err_msg = 2;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string err_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errCode_ = com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode.ERR_OK;
      errMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrMsgBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrMsgBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse, Builder>
        implements com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponseOrBuilder {
      // Construct using com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errCode_ = com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode.ERR_OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse getDefaultInstanceForType() {
        return com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.getDefaultInstance();
      }

      public com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse build() {
        com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse buildPartial() {
        com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse result = new com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMsg_ = errMsg_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse other) {
        if (other == com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.getDefaultInstance()) return this;
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000002;
          errMsg_ = other.errMsg_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;
      private com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode errCode_ = com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode.ERR_OK;
      /**
       * <code>optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;</code>
       */
      public com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;</code>
       */
      public Builder setErrCode(com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errCode_ = value;
        
        return this;
      }
      /**
       * <code>optional .com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse.ErrorCode err_code = 1;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = com.huiyou.dp.service.protocol.Sms.SendIdentifyingCodeResponse.ErrorCode.ERR_OK;
        
        return this;
      }

      // optional string err_msg = 2;
      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string err_msg = 2;</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string err_msg = 2;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string err_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string err_msg = 2;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        
        return this;
      }
      /**
       * <code>optional string err_msg = 2;</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = getDefaultInstance().getErrMsg();
        
        return this;
      }
      /**
       * <code>optional string err_msg = 2;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse)
    }

    static {
      defaultInstance = new SendIdentifyingCodeResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.huiyou.dp.service.protocol.SendIdentifyingCodeResponse)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
